# Generated by Django 2.0.1 on 2019-12-16 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='一级菜单')),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200, verbose_name='图标')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='url名称')),
                ('url', models.CharField(max_length=64, verbose_name='含有正则的url')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='url的别名')),
                ('firstmenu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.FirstMenu', verbose_name='一级菜单')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Icon', verbose_name='图标')),
                ('parent_permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='角色名称')),
                ('permissions', models.ManyToManyField(to='rbac.Permission', verbose_name='所拥有的的权限')),
            ],
        ),
        migrations.AddField(
            model_name='firstmenu',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.Icon', verbose_name='图标'),
        ),
    ]
