# Generated by Django 2.0.1 on 2019-12-21 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20191221_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='class_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.ClassList', verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='讲师'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='tech_teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'depart__title__in': ['教学部']}, related_name='teach_classes', to=settings.AUTH_USER_MODEL, verbose_name='任课老师'),
        ),
    ]
