# Generated by Django 2.0.1 on 2019-12-21 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20191221_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='class_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ClassList', verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='讲师'),
        ),
        migrations.AlterField(
            model_name='homeworkrecord',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='提交时间'),
        ),
    ]
