# Generated by Django 2.0.1 on 2019-12-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20191221_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkrecord',
            name='date',
            field=models.DateField(auto_now=True, null=True, verbose_name='提交时间'),
        ),
    ]
