# Generated by Django 2.0.1 on 2019-12-22 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20191222_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='customer',
        ),
        migrations.AddField(
            model_name='student',
            name='userinfo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户信息'),
        ),
        migrations.AlterField(
            model_name='homeworkrecord',
            name='first_file',
            field=models.FileField(blank=True, null=True, upload_to='homework/', verbose_name='第一次作业'),
        ),
        migrations.AlterField(
            model_name='homeworkrecord',
            name='homework_status',
            field=models.IntegerField(choices=[(1, '未提交'), (2, '已提交')], default=1, verbose_name='作业提交状态'),
        ),
        migrations.AlterField(
            model_name='homeworkrecord',
            name='second_file',
            field=models.FileField(blank=True, null=True, upload_to='homework/', verbose_name='第二次作业'),
        ),
    ]
