# Generated by Django 2.0.1 on 2019-12-23 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20191222_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='consultant',
            field=models.ForeignKey(blank=True, limit_choices_to={'depart__title': '销售部'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='课程顾问'),
        ),
        migrations.AlterField(
            model_name='homeworkrecord',
            name='file',
            field=models.FileField(blank=True, help_text='提交次数最大两次', null=True, upload_to='homework/', verbose_name='作业文件'),
        ),
    ]
